pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/<username>/devops_project.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-html:latest docker/'
            }
        }
        stage('Deploy via Ansible') {
            steps {
                sh 'ansible-playbook ansible/deploy_app.yml -i 192.168.5.136, -u abhishek --become'
            }
        }
    }
    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
