pipeline {
    agent any

    environment {
        IMAGE_NAME = "devops-html"
        IMAGE_TAG = "latest"
        REMOTE_HOST = "192.168.5.136"
        REMOTE_USER = "abhishek"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Abhi1121-linux/devops-html-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Push to Docker') {
            steps {
                echo 'Skipping Docker Hub push for now (optional).'
            }
        }

        stage('Deploy via Ansible') {
            steps {
                ansiblePlaybook(
                    playbook: 'ansible/deploy.yml',
                    inventory: 'ansible/inventory',
                    extras: '-vvv'
                )
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful!"
        }
        failure {
            echo "❌ Deployment failed!"
        }
    }
}
